apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_URL: amRiYzpteXNxbDovL2RhdGFiYXNlLTIuY2d4cm9vZ212b2hnLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTozMzA2L3Rhc2tz
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: Q3Jpc3RpYW5vMDc=
  TOKEN_KEY: YThiOGNlOWI2MTkxY2ZhMzU4MjI5MTdiMWEyNTViMzk2M2QwZDUzYzI0ZmY3MjYzYWQ5NDVmNTRhZTE0OWZlOQ==
